security:
  oauth2:
    client:
      clientId: UOo5D64kcn52StfmoWethhD36ZUa
      #clientSecret: eb004d15f2972041eb21c45afc464ad1
      accessTokenUri: https://graph.facebook.com/oauth/access_token
      userAuthorizationUri: https://www.facebook.com/dialog/oauth
      tokenName: oauth_token
      authenticationScheme: query
      clientAuthenticationScheme: form
    resource:
      userInfoUri: https://graph.facebook.com/me
server:
  port: 0